controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController

arm_controller:
  ros__parameters:
    joints:
      - shoulder_rotation
      - shoulder_pitch
      - elbow
      - wrist_pitch
      - wrist_roll
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    # Trajectory execution parameters
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: false
    
    # More permissive goal tolerance and longer timeouts
    constraints:
      stopped_velocity_tolerance: 0.1   # Increased from 0.05
      goal_time: 5.0                   # Increased from 2.0 - more time for large movements
      shoulder_rotation:
        trajectory: 0.15  # Increased from 0.1 
        goal: 0.08        # Increased from 0.05
      shoulder_pitch:
        trajectory: 0.15  # Increased from 0.1 - this was the problematic joint
        goal: 0.08        # Increased from 0.05
      elbow:
        trajectory: 0.15  # Increased from 0.1
        goal: 0.08        # Increased from 0.05
      wrist_pitch:
        trajectory: 0.15  # Increased from 0.1
        goal: 0.08        # Increased from 0.05
      wrist_roll:
        trajectory: 0.15  # Increased from 0.1
        goal: 0.08        # Increased from 0.05

gripper_controller:
  ros__parameters:
    joint: gripper_joint
    action_monitor_rate: 20.0
    goal_tolerance: 0.02      # Increased from 0.01
    max_effort: 16.5
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 2.0        # Increased from 1.0
