# Joint limits for SO-ARM101
# These limits match the original SO-ARM101 CAD model
# Updated with faster velocity/acceleration limits for testing

default_velocity_scaling_factor: 0.3
default_acceleration_scaling_factor: 0.3

joint_limits:
  shoulder_rotation:
    has_velocity_limits: true
    max_velocity: 3.0        # Increased from 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0    # Increased from 2.0
    has_position_limits: true
    min_position: -1.91986  # -110 degrees
    max_position: 1.91986   # +110 degrees
    
  shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 3.0        # Increased from 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0    # Increased from 2.0
    has_position_limits: true
    min_position: -1.74533  # -100 degrees
    max_position: 1.74533   # +100 degrees
    
  elbow:
    has_velocity_limits: true
    max_velocity: 3.0        # Increased from 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0    # Increased from 2.0
    has_position_limits: true
    min_position: -1.74533  # -100 degrees
    max_position: 1.74533   # +100 degrees
    
  wrist_pitch:
    has_velocity_limits: true
    max_velocity: 3.0        # Increased from 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0    # Increased from 2.0
    has_position_limits: true
    min_position: -1.65806  # -95 degrees
    max_position: 1.65806   # +95 degrees
    
  wrist_roll:
    has_velocity_limits: true
    max_velocity: 3.0        # Increased from 2.0
    has_acceleration_limits: true
    max_acceleration: 3.0    # Increased from 2.0
    has_position_limits: true
    min_position: -2.79253  # -160 degrees
    max_position: 2.79253   # +160 degrees
    
  gripper_joint:
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 2.0
    has_position_limits: true
    min_position: -0.174533  # -10 degrees
    max_position: 1.74533    # +100 degrees
